# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexfile',
            old_name='processed',
            new_name='complete',
        ),
        migrations.RemoveField(
            model_name='indexfile',
            name='processed_rows',
        ),
        migrations.RemoveField(
            model_name='indexfile',
            name='total_rows',
        ),
        migrations.AlterField(
            model_name='index',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
