# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_stocks', '0002_auto_20160222_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='load',
        ),
        migrations.AlterField(
            model_name='company',
            name='ticker',
            field=models.CharField(blank=True, db_column=b'ticker', db_index=True, help_text='Trading symbol of the security.', max_length=15, null=True, verbose_name='ticker'),
        ),
    ]
